pipeline {
    agent any
    environment {
        CI = 'true'
        NODE_OPTIONS = '--openssl-legacy-provider'
    }
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Build') {
            steps {
                sh 'pnpm install'
            }
        }
        stage('Test') {
            steps {
                sh '''
                    chmod +x ./jenkins/scripts/test.sh
                    ./jenkins/scripts/test.sh
                '''
            }
        }
        stage('Deliver') {
            steps {
                sh '''
                    chmod +x ./jenkins/scripts/deliver.sh
                    ./jenkins/scripts/deliver.sh
                '''
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                sh '''
                    chmod +x ./jenkins/scripts/kill.sh
                    ./jenkins/scripts/kill.sh
                '''
            }
        }
    }
}